# Generated by Django 4.1.5 on 2023-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_transacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='CPF',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='data',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
